max_num_landmarks: 6
horizon: 1800
tau: 0.5

target_params:
  init_pos:
    min: -1000
    max: 1000
  init_vel:
    min: -3
    max: 3
  q:
    min: 0.0001
    max: 0.0005
  init_pos_cov:
    min: 100
    max: 1000
  init_vel_cov:
    min: 0.1
    max: 0.25

FoV:
  radius: 50
  obs_pos_cov: 100

lr: 0.0003
max_epoch: 5000
batch_size: 10
num_test_trials: 20
kappa: 0.5